prefix : <http://PAonto.com#> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT DISTINCT ?res ?feat ?proc ?rC WHERE {
	?res :capableOf ?proc . 
	?proc :realizes ?feat ; 
		:requiredCapacity ?rC . 
} ORDER BY ?res ?feat ?proc ?rC